"""create tables

Revision ID: dcfb68d52d5f
Revises: 
Create Date: 2026-05-13 11:22:38.019952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcfb68d52d5f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'tittle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idea')
    # ### end Alembic commands ###
